### ISSUE TITLE
Docker Compose: digitalbank and digitalcredit are mapped to the same host port

### ISSUE THREAD

**Issue by AutomicDemo** [asburymr/Digital-Bank#19]
In the docker compose files for Digital-Bank the "credit:" and "bank:" service both map to the same host port:
`credit: 
   . . .
   ports:
      - "3500:8080"
 bank: 
    . . .
    ports: 
      - "8080:8080"`
Since the 'bank' service is last it gets all the traffic. Bank and Credit will still work fine together since they use Queues, but any external attempt to interact or test the credit service directly will fail with a 404 error.

**Comment by asburymr** [comment]
Can you clarify the issue? Below is how it works today. Let me know if this helps or you are still experiencing an issue with the current configuration.

Digital Bank is mapping the internal container port of 8080 to the docker host machine port 8080. Digital Credit is mapping internal container port of 8080 to the docker host machine port 3500. These ports should not conflict with each other. 

Digital Bank is access the Digital Credit service on the container network on port 8080 which is fine. However if you want to access the Digital Credit API from external to the Docker network (i.e. container to container communication) then you would be access Digital Credit using the docker host port 3500. http://[dockerhost]:3500/credit/swagger-ui.html.

**Comment by AutomicDemo** [comment]
Dammit, never mind. My 1AM in the morning addled brain mixed this up. Got the port order reversed while looking for a culprit to a GCP firewall port-priority problem. In real life I frequently mix up my left and right too. 
Sorry to bother you :)
